bypass environment check for help
* the list command has changed to only list files by default
fix some bugs

diff --git a/mulle-sde b/mulle-sde
--- a/mulle-sde
+++ b/mulle-sde
@@ -141,6 +141,7 @@ print_commands()
       HIDDEN_COMMANDS="\
    craftstatus    : show the craft status of the dependencies
    definition     : change projects craft options like CFLAGS (experimental)
+   donefile       : show contents of donefiles
    crun           : craft and run if project is an executable
    callback       : manage reflect callbacks
    extension      : show available language and buildtool extensions
@@ -362,9 +363,12 @@ is_test_directory()
 
    local directory="$1"
 
-   r_filepath_concat "${directory}" ".mulle/share/test"
+   r_filepath_concat "$1" ".mulle/share/test"
+   directory="${RVAL}"
 
-   rexekutor [ -d "${RVAL}" ]
+   log_debug "directory: ${directory} (${PWD#${MULLE_USER_PWD}/})"
+
+   rexekutor [ -d "${directory}" ]
 }
 
 
@@ -583,6 +587,18 @@ try_to_enter_or_download()
 }
 
 
+is_help_request_commandline()
+{
+   case "$1" in
+      -h|--help|help)
+         return 0
+      ;;
+   esac
+   return 1
+}
+
+
+
 main()
 {
    local MULLE_FLAG_MAGNUM_FORCE='NO'
@@ -743,16 +759,25 @@ status|hostname|uname|show|version|libexec-dir|library-path|project-dir|\
 steal|test|upgrade)
             ;;
 
-            # commands where we want to start a subshell
+            # commands where we want to start a subshell and these don't have
+            # any help text
             addiction-dir|craftorder-kitchen-dir|dependency-dir|kitchen-dir|tool-env|stash-dir)
                exec_command_in_subshell "$@"
             ;;
 
-            callback|clean|craft|craftinfo|craftorder|craftstatus|craft-status|crun|doctor|\
-dependency|definition|env|environment|fetch|files|find|ignore|library|linkorder|list|log|\
+            #
+            # commands that have a help text, we want to show this even
+            # if there is no environment around
+            #
+            callback|clean|craft|craftinfo|craftorder|craftstatus|\
+craft-status|crun|doctor|donefile|dependency|definition|env|environment|fetch|\
+files|find|ignore|library|linkorder|list|log|\
 mark|match|migrate|monitor|patternfile|project|protect|reflect|run|\
 subproject|style|task|tool|treestatus|unmark|unprotect|update)
-               exec_command_in_subshell "$@"
+               if ! is_help_request_commandline "$2"
+               then
+                  exec_command_in_subshell "$@"
+               fi
             ;;
 
             install)
@@ -807,43 +832,46 @@ subproject|style|task|tool|treestatus|unmark|unprotect|update)
       log_trace2 "MULLE_VIRTUAL_ROOT=\"${MULLE_VIRTUAL_ROOT}\""
    fi
 
-   if ! eval `"${MULLE_ENV:-mulle-env}" --search-as-is mulle-tool-env sde`
+   if ! is_help_request_commandline "$@"
    then
-      if [ "${FLAG_OUTSIDE_ENV}" != "YES" ]
+      if ! eval `"${MULLE_ENV:-mulle-env}" --search-as-is mulle-tool-env sde`
       then
-         return 1
-      fi
-      # assume user knows what hes doing
-   else
-      if [ -z "${MULLE_SDE_VAR_DIR}" ]
-      then
-         if [ -z "`pwd -P`" ]
+         if [ "${FLAG_OUTSIDE_ENV}" != "YES" ]
          then
-            fail "The working directory ${PWD} has been deleted"
-         else
-            fail "Mysteriously failed to acquire tool environment"
+            return 1
          fi
-      fi
+         # assume user knows what hes doing
+      else
+         if [ -z "${MULLE_SDE_VAR_DIR}" ]
+         then
+            if [ -z "`pwd -P`" ]
+            then
+               fail "The working directory ${PWD} has been deleted"
+            else
+               fail "Mysteriously failed to acquire tool environment"
+            fi
+         fi
 
-      if [ ! -z "${defines}" ]
-      then
-         set_custom_environment "${defines}"
-      fi
+         if [ ! -z "${defines}" ]
+         then
+            set_custom_environment "${defines}"
+         fi
 
-      local hook
-      local cmdidentifier
+         local hook
+         local cmdidentifier
 
-      # problem here is that cmdidentifier is not validate to be sane
+         # problem here is that cmdidentifier is not validate to be sane
 
-      if [ "${BASH_VERSINFO[0]}" -ge 4 ]
-      then
-         cmdidentifier="${cmd^^}"
-         cmdidentifier="${cmdidentifier//-/_}"
+         if [ "${BASH_VERSINFO[0]}" -ge 4 ]
+         then
+            cmdidentifier="${cmd^^}"
+            cmdidentifier="${cmdidentifier//-/_}"
 
-         hook="MULLE_SDE_${cmdidentifier}_PRELUDE"
+            hook="MULLE_SDE_${cmdidentifier}_PRELUDE"
 
-         # run hook if environment variable is set
-         eval "[ ! -z \"\${${hook}}\" ] && eval \"\${${hook}}\" >&2" >&2
+            # run hook if environment variable is set
+            eval "[ ! -z \"\${${hook}}\" ] && eval \"\${${hook}}\" >&2" >&2
+         fi
       fi
    fi
 
@@ -866,11 +894,14 @@ subproject|style|task|tool|treestatus|unmark|unprotect|update)
       ;;
 
       callback|task)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
-
-         if [ "${PROJECT_TYPE}" = 'none' ]
+         if ! is_help_request_commandline "$@"
          then
-            fail "PROJECT_TYPE is 'none', nothing to ${cmd}"
+            cd_virtual_root_assert_mulle_sde "${cmd}"
+
+            if [ "${PROJECT_TYPE}" = 'none' ]
+            then
+               fail "PROJECT_TYPE is 'none', nothing to ${cmd}"
+            fi
          fi
 
          MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
@@ -881,9 +912,11 @@ subproject|style|task|tool|treestatus|unmark|unprotect|update)
       ;;
 
       clean)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
-
-         assert_test_environment "${cmd}"
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
+            assert_test_environment "${cmd}"
+         fi
 
          # shellcheck source=src/mulle-sde-clean.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-clean.sh"
@@ -950,19 +983,24 @@ version"
       ;;
 
       craft)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
 
-         assert_test_environment "${cmd}"
-
+            assert_test_environment "${cmd}"
+         fi
          # shellcheck source=src/mulle-sde-craft.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-craft.sh"
          sde_craft_main "$@"
       ;;
 
       crun)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
 
-         assert_test_environment "${cmd}"
+            assert_test_environment "${cmd}"
+         fi
 
          # shellcheck source=src/mulle-sde-craft.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-craft.sh"
@@ -970,10 +1008,13 @@ version"
       ;;
 
 
-      craftinfo)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
+      craftinfo|craftinfos)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
 
-         assert_test_environment "${cmd}"
+            assert_test_environment "${cmd}"
+         fi
 
          # shellcheck source=src/mulle-sde-craftinfo.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-craftinfo.sh"
@@ -981,10 +1022,14 @@ version"
          sde_dependency_craftinfo_main "$@"
       ;;
 
-      craftorder)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
+      craftorder|craftorders)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
 
-         assert_test_environment "${cmd}"
+            assert_test_environment "${cmd}"
+         fi
+
 
          # shellcheck source=src/mulle-sde-craftorder.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-craftorder.sh"
@@ -993,21 +1038,27 @@ version"
       ;;
 
       craftstatus|craft-status)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
 
-         assert_test_environment "${cmd}"
+            assert_test_environment "${cmd}"
+         fi
 
          # shellcheck source=src/mulle-sde-craft.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-craft.sh"
          sde_craftstatus_main "$@"
       ;;
 
-      definition)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
-         if [ "${PROJECT_TYPE}" = 'none' ]
+      definition|definitions)
+         if ! is_help_request_commandline "$@"
          then
-            fail "PROJECT_TYPE is 'none', nothing to define"
+            cd_virtual_root_assert_mulle_sde "${cmd}"
+
+            if [ "${PROJECT_TYPE}" = 'none' ]
+            then
+               fail "PROJECT_TYPE is 'none', nothing to define"
+            fi
          fi
 
          # shellcheck source=src/mulle-sde-definition.sh
@@ -1016,23 +1067,33 @@ version"
          sde_definition_main "$@"
       ;;
 
-      dependency)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
+      dependency|dependencies)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         fi
          # shellcheck source=src/mulle-sde-dependency.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-dependency.sh"
 
          sde_dependency_main "$@"
       ;;
 
-     env|environment)
-         cd_virtual_root "environment" 'NO'
+      donefile|donefiles)
+         exekutor "${MULLE_CRAFT:-mulle-craft}" \
+                        ${MULLE_TECHNICAL_FLAGS} \
+                     "${cmd}" "$@"
+      ;;
 
+      env|environment)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root "environment" 'NO'
+         fi
          MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
             exec_mulle_env -N "environment" "$@"
       ;;
 
-      extension)
+      extension|extensions)
          # shellcheck source=src/mulle-sde-extension.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-extension.sh"
 
@@ -1040,21 +1101,36 @@ version"
       ;;
 
       fetch)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
-
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
+         fi
          # shellcheck source=src/mulle-sde-fetch.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-fetch.sh"
 
          sde_fetch_main "$@"
       ;;
 
-      list|files)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
+      files)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         fi
          # shellcheck source=src/mulle-sde-list.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-list.sh"
 
-         sde_list_main --files --no-dependencies --no-environment --no-definitions "$@"
+         sde_list_main --files
+      ;;
+
+      list)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         fi
+         # shellcheck source=src/mulle-sde-list.sh
+         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-list.sh"
+
+         sde_list_main "$@"
       ;;
 
       hostname)
@@ -1087,9 +1163,11 @@ version"
          sde_init_main --no-blurb "$@" && exec_mulle_env
       ;;
 
-      library)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
+      library|libraries)
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         fi
          # shellcheck source=src/mulle-sde-library.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-library.sh"
 
@@ -1101,10 +1179,12 @@ version"
       ;;
 
       linkorder)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO' 'NO'
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO' 'NO'
 
-         assert_test_environment "${cmd}"
-
+            assert_test_environment "${cmd}"
+         fi
          # shellcheck source=src/mulle-sde-dependency.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-linkorder.sh"
 
@@ -1113,9 +1193,12 @@ version"
 
 
       log)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO' 'NO'
 
-         assert_test_environment "${cmd}"
+            assert_test_environment "${cmd}"
+         fi
 
          MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
             exekutor "${MULLE_CRAFT:-mulle-craft}" \
@@ -1125,13 +1208,15 @@ version"
       ;;
 
       match|patternfile)
-         cd_virtual_root "${cmd}" 'NO'
-
-         if [ "${PROJECT_TYPE}" = 'none' ]
+         if ! is_help_request_commandline "$@"
          then
-            fail "PROJECT_TYPE is 'none', nothing to ${cmd}"
-         fi
+            cd_virtual_root "${cmd}" 'NO'
 
+            if [ "${PROJECT_TYPE}" = 'none' ]
+            then
+               fail "PROJECT_TYPE is 'none', nothing to ${cmd}"
+            fi
+         fi
          MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
             exekutor "${MULLE_MATCH:-mulle-match}" \
                            ${MULLE_TECHNICAL_FLAGS} \
@@ -1141,11 +1226,13 @@ version"
 
       # convenient shortcuts
       mark|unmark)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
 
-         # shellcheck source=src/mulle-sde-dependency.sh
-         . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-dependency.sh"
-
+            # shellcheck source=src/mulle-sde-dependency.sh
+            . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-dependency.sh"
+         fi
          sde_dependency_main "${cmd}" "$@"
       ;;
 
@@ -1157,8 +1244,10 @@ version"
       migrate)
          log_warning "Command only to be used for development of mulle-sde"
 
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         fi
          # shellcheck source=src/mulle-sde-migrate.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-migrate.sh"
 
@@ -1166,11 +1255,14 @@ version"
       ;;
 
       monitor)
-         cd_virtual_root "${cmd}"
-
-         if [ "${PROJECT_TYPE}" = 'none' ]
+         if ! is_help_request_commandline "$@"
          then
-            fail "PROJECT_TYPE is 'none', nothing to ${cmd}"
+            cd_virtual_root "${cmd}"
+
+            if [ "${PROJECT_TYPE}" = 'none' ]
+            then
+               fail "PROJECT_TYPE is 'none', nothing to ${cmd}"
+            fi
          fi
 
          # shellcheck source=src/mulle-sde-monitor.sh
@@ -1212,9 +1304,11 @@ version"
       ;;
 
       reflect|update)
-         # must allow NO for subenv updates
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
+         if ! is_help_request_commandline "$@"
+         then
+            # must allow NO for subenv updates
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+         fi
          # shellcheck source=src/mulle-sde-reflect.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-reflect.sh"
 
@@ -1300,12 +1394,15 @@ version"
            exec_mulle_env -N "${cmd}" "$@"
       ;;
 
-      subproject)
-         cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
-
-         if [ "${PROJECT_TYPE}" = 'none' ]
+      subproject|subprojects)
+         if ! is_help_request_commandline "$@"
          then
-            fail "PROJECT_TYPE is 'none', no subprojects are possible"
+            cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
+
+            if [ "${PROJECT_TYPE}" = 'none' ]
+            then
+               fail "PROJECT_TYPE is 'none', no subprojects are possible"
+            fi
          fi
 
          # shellcheck source=src/mulle-sde-subproject.sh
@@ -1315,9 +1412,12 @@ version"
       ;;
 
       test)
-         if [ ! -z "${MULLE_VIRTUAL_ROOT}" ]
+         if ! is_help_request_commandline "$@"
          then
-            rexekutor cd "${MULLE_VIRTUAL_ROOT}" || fail "MULLE_VIRTUAL_ROOT \"${MULLE_VIRTUAL_ROOT}\" is missing"
+            if [ ! -z "${MULLE_VIRTUAL_ROOT}" ]
+            then
+               rexekutor cd "${MULLE_VIRTUAL_ROOT}" || fail "MULLE_VIRTUAL_ROOT \"${MULLE_VIRTUAL_ROOT}\" is missing"
+            fi
          fi
 
          # shellcheck source=src/mulle-sde-test.sh
@@ -1327,8 +1427,10 @@ version"
       ;;
 
       treestatus)
-         cd_virtual_root_assert_mulle_sde "${cmd}"
-
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root_assert_mulle_sde "${cmd}"
+         fi
          MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
             exekutor "${MULLE_SOURCETREE:-mulle-sourcetree}" \
                            --virtual-root \
@@ -1338,8 +1440,10 @@ version"
       ;;
 
       tool)
-         cd_virtual_root "${cmd}"
-
+         if ! is_help_request_commandline "$@"
+         then
+            cd_virtual_root "${cmd}"
+         fi
          MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exec_mulle_env -N "${cmd}" "$@"
       ;;
