* improve install command and especially the usage dox, to make it more transparent how to build static or dynamic product fix reinit command to repopulate with share files * introduce some shortcuts: dep for dependency, lib for library, ext for extension, pat for patternfile, sub for subprojects. Aliases are nice but mulle-sde dep is also nice...

diff --git a/mulle-sde b/mulle-sde
--- a/mulle-sde
+++ b/mulle-sde
@@ -319,11 +319,14 @@ set_custom_environment()
 #
 run_mulle_env()
 {
+   log_entry "exec_mulle_env" "$@"
+
    rexekutor "${MULLE_ENV:-mulle-env}" \
                   ${MULLE_TECHNICAL_FLAGS} \
                   ${MULLE_ENV_FLAGS} \
                   ${MULLE_FWD_FLAGS} \
-                  --defines "${MULLE_DEFINE_FLAGS}" "$@"
+                  --defines "${MULLE_DEFINE_FLAGS}" \
+                  "$@"
 }
 
 
@@ -332,28 +335,17 @@ run_mulle_env()
 #
 exec_mulle_env()
 {
+   log_entry "exec_mulle_env" "$@"
+
    rexekutor exec "${MULLE_ENV:-mulle-env}" \
                        ${MULLE_TECHNICAL_FLAGS} \
                        ${MULLE_ENV_FLAGS} \
                        ${MULLE_FWD_FLAGS} \
-                       --defines "${MULLE_DEFINE_FLAGS}" "$@"
+                       --defines "${MULLE_DEFINE_FLAGS}" \
+                       "$@"
 }
 
 
-
-
-#
-# here we are just bouncing through mulle-env, we don't want
-# to pass -n, so mulle-env does nothing. So pushing MULLE_TECHNICAL_FLAGS
-# unfiltered isn't good. The technical flags will be part of the incoming
-# command line in "$@"
-#
-exec_mulle_env_bounce()
-{
-   rexekutor exec "${MULLE_ENV:-mulle-env}" \
-                       ${MULLE_ENV_FLAGS} \
-                       --defines "${MULLE_DEFINE_FLAGS}" "$@"
-}
 
 
 r_determine_project_dir()
@@ -417,11 +409,9 @@ assert_test_environment()
 }
 
 
-_exec_command_in_subshell()
+exec_command_in_subshell()
 {
-   log_entry "_exec_command_in_subshell" "$@"
-
-   local cmdline="$1"; shift
+   log_entry "exec_command_in_subshell" "$@"
 
    local current
 
@@ -451,6 +441,9 @@ ${C_RESET_BOLD}   mulle-sde init"
    # picked up by MULLE_ENV
    #
    local flag
+   local cmdline
+
+   cmdline="${MULLE_EXECUTABLE}"
 
    shell_disable_glob # keep it
    for flag in ${MULLE_TECHNICAL_FLAGS} ${MULLE_FWD_FLAGS}
@@ -466,21 +459,19 @@ $1"
       shift
    done
 
-   MULLE_USAGE_NAME="mulle-sde" exec_mulle_env_bounce -C "${cmdline}"
-}
 
-
-
-#
-# This reruns a mulle-sde command via mulle-env, so effectively calling
-# this script with the same parameters again, but from inside the environment
-#
-exec_command_in_subshell()
-{
-   log_entry "exec_command_in_subshell" "$@"
-
-   _exec_command_in_subshell "${MULLE_EXECUTABLE}" "$@"
-   exit $?
+   #
+   # here we are just bouncing through mulle-env, we don't want
+   # to pass -n, so mulle-env does nothing. So pushing MULLE_TECHNICAL_FLAGS
+   # unfiltered isn't good. The technical flags will be part of the incoming
+   # command line in "$@"
+   #
+   MULLE_USAGE_NAME="mulle-sde" \
+      rexekutor exec "${MULLE_ENV:-mulle-env}" \
+                        ${MULLE_ENV_FLAGS} \
+                        ${MULLE_FWD_FLAGS} \
+                        --defines "${MULLE_DEFINE_FLAGS}" \
+                        -C "${cmdline}"
 }
 
 
@@ -525,7 +516,8 @@ cd_virtual_root()
       then
          if [ "${subenvwarn}" = 'YES' ]
          then
-            log_warning "\"${MULLE_VIRTUAL_ROOT}\" is virtual root, but we are in a subshell already ($physdir)"
+            log_warning "\"${MULLE_VIRTUAL_ROOT}\" is virtual root, but we are \
+in a subshell already ($physdir)"
          fi
       else
          physdir="${MULLE_VIRTUAL_ROOT}"
@@ -535,7 +527,8 @@ cd_virtual_root()
    # ensure that we are in physical
    if [ "${physdir}" != "${PWD}" ]
    then
-      rexekutor cd "${physdir}" || fail "could not enter physical virtual root (${MULLE_VIRTUAL_ROOT})"
+      rexekutor cd "${physdir}" \
+      || fail "could not enter physical virtual root (${MULLE_VIRTUAL_ROOT})"
    fi
 
    # set MULLE_VIRTUAL_ROOT to physical (can have changed above intermittently)
@@ -552,7 +545,8 @@ cd_virtual_root_assert_mulle_sde()
       return
    fi
 
-   [ ! -d "${MULLE_SDE_SHARE_DIR}" ] && fail "There is no ${MULLE_SDE_SHARE_DIR} here"
+   [ ! -d "${MULLE_SDE_SHARE_DIR}" ] \
+   && fail "There is no ${MULLE_SDE_SHARE_DIR} here"
 }
 
 
@@ -760,8 +754,8 @@ main()
       then
          case "${cmd}" in
             # commands that do not need a subshell (immediately)
-            add|bash-completion|commands|extension|init|init-and-enter|reinit|\
-status|hostname|uname|show|version|libexec-dir|library-path|project-dir|\
+            add|bash-completion|commands|extension|init|init-and-enter|install|\
+reinit|status|hostname|uname|show|version|libexec-dir|library-path|project-dir|\
 steal|test|upgrade)
             ;;
 
@@ -779,14 +773,15 @@ steal|test|upgrade)
 craft-status|crun|doctor|donefile|dependency|definition|env|environment|fetch|\
 files|find|ignore|library|linkorder|list|log|\
 mark|match|migrate|monitor|patternfile|project|protect|reflect|run|\
-sourcetree|subproject|style|task|tool|treestatus|unmark|unprotect|update)
+sourcetree|subproject|style|task|tool|treestatus|unmark|unprotect|update|\
+dep|ext|lib|pat|sub)
                if ! is_help_request_commandline "$2"
                then
                   exec_command_in_subshell "$@"
                fi
             ;;
 
-            install)
+            _install)
                # shellcheck source=src/mulle-sde-install.sh
                . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-install.sh"
 
@@ -957,6 +952,7 @@ find
 ignore
 init
 init-and-enter
+install_in_tmp
 kitchen-dir
 libexec-dir
 library
@@ -1071,7 +1067,7 @@ version"
          sde_craftstatus_main "$@"
       ;;
 
-      definition|definitions)
+      definition|definitions|def)
          if ! is_help_request_commandline "$@"
          then
             cd_virtual_root_assert_mulle_sde "${cmd}"
@@ -1088,7 +1084,7 @@ version"
          sde_definition_main "$@"
       ;;
 
-      dependency|dependencies)
+      dependency|dependencies|dep)
          if ! is_help_request_commandline "$@"
          then
             cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
@@ -1105,7 +1101,11 @@ version"
                      "${cmd}" "$@"
       ;;
 
-      env|environment)
+      enter)
+         fail "Command must be run from outside of the current environment."
+      ;;
+
+      environment|env)
          if ! is_help_request_commandline "$@"
          then
             cd_virtual_root "environment" 'NO'
@@ -1114,7 +1114,7 @@ version"
             exec_mulle_env -N "environment" "$@"
       ;;
 
-      extension|extensions)
+      extension|extensions|ext)
          # shellcheck source=src/mulle-sde-extension.sh
          . "${MULLE_SDE_LIBEXEC_DIR}/mulle-sde-extension.sh"
 
@@ -1184,7 +1184,21 @@ version"
          sde_init_main --no-blurb "$@" && exec_mulle_env
       ;;
 
-      library|libraries)
+
+      install)
+         # invoke ourselves with a clean environment so that we
+         # don't accidentally inherit something from the current
+         # environment. If you use -n, it won't work. This is not a "bounce"
+         # though
+         exec_mulle_env invoke "${MULLE_EXECUTABLE}" \
+                               ${MULLE_TECHNICAL_FLAGS} \
+                               ${MULLE_FWD_FLAGS} \
+                           _install \
+                                 "$@"
+         return $?
+      ;;
+
+      library|libraries|lib)
          if ! is_help_request_commandline "$@"
          then
             cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
@@ -1228,7 +1242,7 @@ version"
                            "$@"
       ;;
 
-      match|patternfile)
+      match|patternfile|pat)
          if ! is_help_request_commandline "$@"
          then
             cd_virtual_root "${cmd}" 'NO'
@@ -1415,7 +1429,7 @@ version"
            exec_mulle_env -N "${cmd}" "$@"
       ;;
 
-      subproject|subprojects)
+      subproject|subprojects|sub)
          if ! is_help_request_commandline "$@"
          then
             cd_virtual_root_assert_mulle_sde "${cmd}" 'NO'
@@ -1437,7 +1451,8 @@ version"
          then
             if [ ! -z "${MULLE_VIRTUAL_ROOT}" ]
             then
-               rexekutor cd "${MULLE_VIRTUAL_ROOT}" || fail "MULLE_VIRTUAL_ROOT \"${MULLE_VIRTUAL_ROOT}\" is missing"
+               rexekutor cd "${MULLE_VIRTUAL_ROOT}" \
+               || fail "MULLE_VIRTUAL_ROOT \"${MULLE_VIRTUAL_ROOT}\" is missing"
             fi
          fi
 
@@ -1492,9 +1507,6 @@ version"
          return 0
       ;;
 
-      enter|install)
-         fail "Command must be run from outside of the current environment."
-      ;;
 
       *)
          if [ -d "${cmd}" ]
@@ -1529,6 +1541,12 @@ ${C_RESET_BOLD}exit${C_ERROR} the current environment."
 ###
 ### INIT
 ###
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    # leading backslash ? looks like we're getting called from
@@ -1547,17 +1565,15 @@ _init()
       then
          if [ -z "`command -v "${executablepath}"`" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
-         else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
+            _fatal "mulle-bashfunctions-env not installed"
          fi
-         exit 1
+         _fatal "Could not find libexec of mulle-bashfunctions-env"
       fi
    fi
 
       # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
-      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || \
+      _fatal "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
 
    if [ -z "${MULLE_SDE_LIBEXEC_DIR}" ]
    then
