* use / as vendor extension separator instead of : * added bash completion * adapt to changes in inferior tools

diff --git a/src/extensions/mulle-sde/sde/init b/src/extensions/mulle-sde/sde/init
--- a/src/extensions/mulle-sde/sde/init
+++ b/src/extensions/mulle-sde/sde/init
@@ -1,16 +1,19 @@
-#! /bin/sh
+#! /usr/bin/env bash
 
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
-fgrep -q -s 'generated by mulle-sde' .gitignore
-case $? in
-   0)
-      exit 0
-   ;;
-esac
+
+setup_gitignore()
+{
+   fgrep -q -s 'generated by mulle-sde' .gitignore
+   case $? in
+      0)
+         return 0
+      ;;
+   esac
 
 
-cat <<EOF >> .gitignore
+   text='.gitignore
 
 # ### > generated by mulle-sde (extensions/mulle-sde/sde/init)
 
@@ -32,5 +35,80 @@ cat <<EOF >> .gitignore
 !.mulle-sourcetree/etc
 
 # ### < generated by mulle-sde (extensions/sde/init)
+'
 
-EOF
+   redirect_append_exekutor .gitignore echo "${text}"
+}
+
+
+install_bash_completion()
+{
+   local filename
+
+   local text
+
+   text='\
+#! /usr/bin/env bash
+
+#
+# install completion if not yet present.
+# mulle-sde-bash-completion.sh will load the inferior completes
+#
+if [ "`type -t "_mulle_sde_complete"`" != "function" ]
+then
+   . "$(mulle-sde libexec-dir)/mulle-sde-bash-completion.sh"
+fi
+'
+
+   local dstdir
+
+   chmod -R ug+wX ".mulle-env/share"
+
+   dstdir=".mulle-env/share/libexec"
+
+   mkdir_if_missing "${dstdir}"
+   redirect_exekutor "${dstdir}/load-bash-completion.sh" echo "${text}"
+
+   chmod -R a-w ".mulle-env/share"
+}
+
+
+main()
+{
+   setup_gitignore
+   install_bash_completion
+}
+
+########
+###
+### INIT
+###
+_init()
+{
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+      then
+         if [ -z "`command -v "mulle-bashfunctions-env"`" ]
+         then
+            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+         else
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+         fi
+         exit 1
+      fi
+   fi
+
+   # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"  || \
+      ( echo "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" >&2 )
+}
+###
+### INIT
+###
+########
+
+
+_init "$@" # needs params
+main "$@"
